//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "addressExt"
	/// <summary>AddressExt</summary>
	public partial interface IAddressExt : IPublishedElement
	{
		/// <summary>City Code</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent CityCode { get; }

		/// <summary>Town Code</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent TownCode { get; }
	}

	/// <summary>AddressExt</summary>
	[PublishedModel("addressExt")]
	public partial class AddressExt : PublishedElementModel, IAddressExt
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const string ModelTypeAlias = "addressExt";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AddressExt, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public AddressExt(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// City Code: 縣市代碼
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("cityCode")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent CityCode => GetCityCode(this);

		/// <summary>Static getter for City Code</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetCityCode(IAddressExt that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("cityCode");

		///<summary>
		/// Town Code: 鄉鎮市區代碼
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("townCode")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent TownCode => GetTownCode(this);

		/// <summary>Static getter for Town Code</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetTownCode(IAddressExt that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("townCode");
	}
}
