//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Agency</summary>
	[PublishedModel("agency")]
	public partial class Agency : PublishedContentModel, IContactPersonControl
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const string ModelTypeAlias = "agency";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Agency, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Agency(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Accreditation Type: 評鑑類別
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("accreditationType")]
		public string AccreditationType => this.Value<string>("accreditationType");

		///<summary>
		/// Agency Alias: 機構簡稱
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("agencyAlias")]
		public string AgencyAlias => this.Value<string>("agencyAlias");

		///<summary>
		/// Agency Author: 機構權屬別
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("agencyAuthor")]
		public string AgencyAuthor => this.Value<string>("agencyAuthor");

		///<summary>
		/// Agency ID: 機構代碼-健保
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("agencyID")]
		public string AgencyID => this.Value<string>("agencyID");

		///<summary>
		/// Agency Name: 機構名稱
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("agencyName")]
		public string AgencyName => this.Value<string>("agencyName");

		///<summary>
		/// Agency Type: 經營型態
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("agencyType")]
		public string AgencyType => this.Value<string>("agencyType");

		///<summary>
		/// Is HQ: 是否為本院
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("isHQ")]
		public bool IsHQ => this.Value<bool>("isHQ");

		///<summary>
		/// Contact Department: 聯絡人部門
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactDepartment")]
		public string ContactDepartment => global::Umbraco.Web.PublishedModels.ContactPersonControl.GetContactDepartment(this);

		///<summary>
		/// Contact eMail: 聯絡人電子郵件
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactEMail")]
		public string ContactEmail => global::Umbraco.Web.PublishedModels.ContactPersonControl.GetContactEmail(this);

		///<summary>
		/// Contact ID: 聯絡人身份證號
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactID")]
		public string ContactID => global::Umbraco.Web.PublishedModels.ContactPersonControl.GetContactID(this);

		///<summary>
		/// Contact Mobile: 聯絡人手機
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactMobile")]
		public string ContactMobile => global::Umbraco.Web.PublishedModels.ContactPersonControl.GetContactMobile(this);

		///<summary>
		/// Contact Name: 聯絡人姓名
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactName")]
		public string ContactName => global::Umbraco.Web.PublishedModels.ContactPersonControl.GetContactName(this);

		///<summary>
		/// Contact TEL - Office: 聯絡人電話
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactTELOffice")]
		public string ContactTeloffice => global::Umbraco.Web.PublishedModels.ContactPersonControl.GetContactTeloffice(this);

		///<summary>
		/// Contact TEL-Office-Extension: 聯絡人電話分機
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactTELOfficeExtension")]
		public string ContactTelofficeExtension => global::Umbraco.Web.PublishedModels.ContactPersonControl.GetContactTelofficeExtension(this);

		///<summary>
		/// Contact Title: 聯絡人職稱
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactTitle")]
		public string ContactTitle => global::Umbraco.Web.PublishedModels.ContactPersonControl.GetContactTitle(this);
	}
}
