//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "codeSystem"
	/// <summary>Code System</summary>
	public partial interface ICodeSystem : IPublishedContent
	{
		/// <summary>Code System ID</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string CodeSystemID { get; }

		/// <summary>Code System Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string CodeSystemName { get; }

		/// <summary>Code System OID</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string CodeSystemOid { get; }

		/// <summary>Code System Source</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string CodeSystemSource { get; }

		/// <summary>Code System URI</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string CodeSystemUri { get; }
	}

	/// <summary>Code System</summary>
	[PublishedModel("codeSystem")]
	public partial class CodeSystem : PublishedContentModel, ICodeSystem
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const string ModelTypeAlias = "codeSystem";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CodeSystem, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CodeSystem(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Code System ID: 編碼系統之ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("codeSystemID")]
		public string CodeSystemID => GetCodeSystemID(this);

		/// <summary>Static getter for Code System ID</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetCodeSystemID(ICodeSystem that) => that.Value<string>("codeSystemID");

		///<summary>
		/// Code System Name: 編碼系統名稱
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("codeSystemName")]
		public string CodeSystemName => GetCodeSystemName(this);

		/// <summary>Static getter for Code System Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetCodeSystemName(ICodeSystem that) => that.Value<string>("codeSystemName");

		///<summary>
		/// Code System OID: 編碼系統OID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("codeSystemOID")]
		public string CodeSystemOid => GetCodeSystemOid(this);

		/// <summary>Static getter for Code System OID</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetCodeSystemOid(ICodeSystem that) => that.Value<string>("codeSystemOID");

		///<summary>
		/// Code System Source: 編碼系統來源
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("codeSystemSource")]
		public string CodeSystemSource => GetCodeSystemSource(this);

		/// <summary>Static getter for Code System Source</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetCodeSystemSource(ICodeSystem that) => that.Value<string>("codeSystemSource");

		///<summary>
		/// Code System URI: 編碼系統URI
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("codeSystemURI")]
		public string CodeSystemUri => GetCodeSystemUri(this);

		/// <summary>Static getter for Code System URI</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetCodeSystemUri(ICodeSystem that) => that.Value<string>("codeSystemURI");
	}
}
