//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "contactPersonControl"
	/// <summary>Contact Person Control</summary>
	public partial interface IContactPersonControl : IPublishedContent
	{
		/// <summary>Contact Department</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string ContactDepartment { get; }

		/// <summary>Contact eMail</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string ContactEmail { get; }

		/// <summary>Contact ID</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string ContactID { get; }

		/// <summary>Contact Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string ContactMobile { get; }

		/// <summary>Contact Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string ContactName { get; }

		/// <summary>Contact TEL - Office</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string ContactTeloffice { get; }

		/// <summary>Contact TEL-Office-Extension</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string ContactTelofficeExtension { get; }

		/// <summary>Contact Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string ContactTitle { get; }
	}

	/// <summary>Contact Person Control</summary>
	[PublishedModel("contactPersonControl")]
	public partial class ContactPersonControl : PublishedContentModel, IContactPersonControl
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const string ModelTypeAlias = "contactPersonControl";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactPersonControl, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ContactPersonControl(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Contact Department: 聯絡人部門
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactDepartment")]
		public string ContactDepartment => GetContactDepartment(this);

		/// <summary>Static getter for Contact Department</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetContactDepartment(IContactPersonControl that) => that.Value<string>("contactDepartment");

		///<summary>
		/// Contact eMail: 聯絡人電子郵件
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactEMail")]
		public string ContactEmail => GetContactEmail(this);

		/// <summary>Static getter for Contact eMail</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetContactEmail(IContactPersonControl that) => that.Value<string>("contactEMail");

		///<summary>
		/// Contact ID: 聯絡人身份證號
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactID")]
		public string ContactID => GetContactID(this);

		/// <summary>Static getter for Contact ID</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetContactID(IContactPersonControl that) => that.Value<string>("contactID");

		///<summary>
		/// Contact Mobile: 聯絡人手機
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactMobile")]
		public string ContactMobile => GetContactMobile(this);

		/// <summary>Static getter for Contact Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetContactMobile(IContactPersonControl that) => that.Value<string>("contactMobile");

		///<summary>
		/// Contact Name: 聯絡人姓名
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactName")]
		public string ContactName => GetContactName(this);

		/// <summary>Static getter for Contact Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetContactName(IContactPersonControl that) => that.Value<string>("contactName");

		///<summary>
		/// Contact TEL - Office: 聯絡人電話
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactTELOffice")]
		public string ContactTeloffice => GetContactTeloffice(this);

		/// <summary>Static getter for Contact TEL - Office</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetContactTeloffice(IContactPersonControl that) => that.Value<string>("contactTELOffice");

		///<summary>
		/// Contact TEL-Office-Extension: 聯絡人電話分機
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactTELOfficeExtension")]
		public string ContactTelofficeExtension => GetContactTelofficeExtension(this);

		/// <summary>Static getter for Contact TEL-Office-Extension</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetContactTelofficeExtension(IContactPersonControl that) => that.Value<string>("contactTELOfficeExtension");

		///<summary>
		/// Contact Title: 聯絡人職稱
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("contactTitle")]
		public string ContactTitle => GetContactTitle(this);

		/// <summary>Static getter for Contact Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetContactTitle(IContactPersonControl that) => that.Value<string>("contactTitle");
	}
}
