//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Contact Point</summary>
	[PublishedModel("contactPoint")]
	public partial class ContactPoint : PublishedElementModel, IContactPointExt
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const string ModelTypeAlias = "contactPoint";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactPoint, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ContactPoint(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Period: 有效期間
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("period")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.Period> Period => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.Period>>("period");

		///<summary>
		/// Rank: 等級，優先序
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("rank")]
		public int Rank => this.Value<int>("rank");

		///<summary>
		/// System: 通訊系統
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("system")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent System => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("system");

		///<summary>
		/// Use: 使用點
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("use")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Use => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("use");

		///<summary>
		/// Value: 通訊內容值
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("value")]
		public string Value => this.Value<string>("value");

		///<summary>
		/// Extension
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("extension")]
		public string Extension => global::Umbraco.Web.PublishedModels.ContactPointExt.GetExtension(this);
	}
}
