//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Contacts</summary>
	[PublishedModel("contacts")]
	public partial class Contacts : PublishedContentModel, IPersonControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const string ModelTypeAlias = "contacts";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Contacts, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Contacts(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Person Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("personAddress")]
		public global::Umbraco.Web.PublishedModels.AddressElement PersonAddress => global::Umbraco.Web.PublishedModels.PersonControls.GetPersonAddress(this);

		///<summary>
		/// Person Identify: 辨識資料
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("personIdentify")]
		public global::Umbraco.Web.PublishedModels.IdentifyElement PersonIdentify => global::Umbraco.Web.PublishedModels.PersonControls.GetPersonIdentify(this);

		///<summary>
		/// Person Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("personName")]
		public global::Umbraco.Web.PublishedModels.NameElement PersonName => global::Umbraco.Web.PublishedModels.PersonControls.GetPersonName(this);

		///<summary>
		/// Person Occupation: 職業內容
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("personOccupation")]
		public global::Umbraco.Web.PublishedModels.OccupationElement PersonOccupation => global::Umbraco.Web.PublishedModels.PersonControls.GetPersonOccupation(this);

		///<summary>
		/// Person TEL: 通訊模組
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("personTEL")]
		public global::Umbraco.Web.PublishedModels.TelElement PersonTel => global::Umbraco.Web.PublishedModels.PersonControls.GetPersonTel(this);
	}
}
