//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Identifier</summary>
	[PublishedModel("identifier")]
	public partial class Identifier : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const string ModelTypeAlias = "identifier";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Identifier, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Identifier(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Assigner
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("assigner")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Assigner => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("assigner");

		///<summary>
		/// Period
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("period")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.Period> Period => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.Period>>("period");

		///<summary>
		/// System
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("system")]
		public string System => this.Value<string>("system");

		///<summary>
		/// Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("type")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CodeableConcept> Type => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CodeableConcept>>("type");

		///<summary>
		/// Use: 使用情境
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("use")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Use => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("use");

		///<summary>
		/// Value
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("value")]
		public string Value => this.Value<string>("value");
	}
}
