//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "personControls"
	/// <summary>Person Controls</summary>
	public partial interface IPersonControls : IPublishedContent
	{
		/// <summary>Person Address</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		global::Umbraco.Web.PublishedModels.AddressElement PersonAddress { get; }

		/// <summary>Person Identify</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		global::Umbraco.Web.PublishedModels.IdentifyElement PersonIdentify { get; }

		/// <summary>Person Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		global::Umbraco.Web.PublishedModels.NameElement PersonName { get; }

		/// <summary>Person Occupation</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		global::Umbraco.Web.PublishedModels.OccupationElement PersonOccupation { get; }

		/// <summary>Person TEL</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		global::Umbraco.Web.PublishedModels.TelElement PersonTel { get; }
	}

	/// <summary>Person Controls</summary>
	[PublishedModel("personControls")]
	public partial class PersonControls : PublishedContentModel, IPersonControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const string ModelTypeAlias = "personControls";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PersonControls, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PersonControls(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Person Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("personAddress")]
		public global::Umbraco.Web.PublishedModels.AddressElement PersonAddress => GetPersonAddress(this);

		/// <summary>Static getter for Person Address</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static global::Umbraco.Web.PublishedModels.AddressElement GetPersonAddress(IPersonControls that) => that.Value<global::Umbraco.Web.PublishedModels.AddressElement>("personAddress");

		///<summary>
		/// Person Identify: 辨識資料
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("personIdentify")]
		public global::Umbraco.Web.PublishedModels.IdentifyElement PersonIdentify => GetPersonIdentify(this);

		/// <summary>Static getter for Person Identify</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static global::Umbraco.Web.PublishedModels.IdentifyElement GetPersonIdentify(IPersonControls that) => that.Value<global::Umbraco.Web.PublishedModels.IdentifyElement>("personIdentify");

		///<summary>
		/// Person Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("personName")]
		public global::Umbraco.Web.PublishedModels.NameElement PersonName => GetPersonName(this);

		/// <summary>Static getter for Person Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static global::Umbraco.Web.PublishedModels.NameElement GetPersonName(IPersonControls that) => that.Value<global::Umbraco.Web.PublishedModels.NameElement>("personName");

		///<summary>
		/// Person Occupation: 職業內容
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("personOccupation")]
		public global::Umbraco.Web.PublishedModels.OccupationElement PersonOccupation => GetPersonOccupation(this);

		/// <summary>Static getter for Person Occupation</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static global::Umbraco.Web.PublishedModels.OccupationElement GetPersonOccupation(IPersonControls that) => that.Value<global::Umbraco.Web.PublishedModels.OccupationElement>("personOccupation");

		///<summary>
		/// Person TEL: 通訊模組
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("personTEL")]
		public global::Umbraco.Web.PublishedModels.TelElement PersonTel => GetPersonTel(this);

		/// <summary>Static getter for Person TEL</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static global::Umbraco.Web.PublishedModels.TelElement GetPersonTel(IPersonControls that) => that.Value<global::Umbraco.Web.PublishedModels.TelElement>("personTEL");
	}
}
